### ISSUE TITLE
Issue on backup -> Database restore: Failed to insert row from...

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson-Backups-Extension#32]
Hi there, 

We've a customer having some issues during the backup that we can't figure out so far. 

Here is what we see from the log : 

<pre>
Database restore: Failed to insert row from line 110 into table _fwbk_wp_xxxxx_comments | 
{"comment_ID":"52","comment_post_ID":"1683","comment_author":"Melissa 
Doe","comment_author_email":"email@yahoo.com","comment_author_url":"","comment_author_IP":
"58.107.173.118","comment_date":"2016-09-13 23:14:18","comment_date_gmt":"2016-09-13 
13:14:18","comment_content":"Ummmmm in the wiki PJ? 
\ud83d\ude1c","comment_karma":"0","comment_approved":"1","comment_agent":"Mozilla\/5.0 
(iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit\/600.1.4 (KHTML, like Gecko) 
GSA\/18.1.132077863 Mobile\/13G36 Safari\/600.1.4","comment_type":"","comment_parent":"0","user_id":"34"}
</pre>

Anything we might have missed ? 

Cheers !

**Comment by moldcraft** [comment]
Hello,

1. Are you sure this is the complete error message? [This](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.15/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L869) should print more details.
2. Can you send me the access credentials?
3. Please update Unyson extensions because the part that displays `| {"comment_ID":"52"...` [was removed](https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/4dd764059e3d4cb8bcbd9f0737384b7b728c9433).

**Comment by 2Fwebd** [comment]
Hi Moldcraft, 

I've updated the extension to the customer's site and so far it seems to work out just fine now. 

I'll let you know if that doesn't work later. But seems resolved for now.

**Comment by 2Fwebd** [comment]
My bad, the issue is still here. I'm sending you all accesses right now.

**Comment by 2Fwebd** [comment]
Any update on that ?

**Comment by moldcraft** [comment]
The problem is in

```
"comment_content":"Ummmmm in the wiki PJ? \ud83d\ude1c"
```

which actually is

```
Ummmmm in the wiki PJ? 😜
```

and another line

```
Petting zoo every month 😉
```

It is [complicated](https://www.google.com/search?q=mysql%20smiley%20face). The only solution is to convert your database to `utf8mb4` encoding (if your server/hosting supports it).

As a temporary solution I have added [here](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/ab8b2ef5145a5777ac544f2cb15b8b3563be4500/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L888)

```
$sql = str_replace(array('😜', '😉'), '', $sql);
```

and Content Backup Restore has finished.
