### ISSUE TITLE
error message timeout on unzip godaddy

### ISSUE THREAD

**Issue by eduplessis** [ThemeFuse/Unyson-Backups-Extension#9]

**Comment by moldcraft** [comment]
Hello,
Which theme and which demo?

**Comment by eduplessis** [comment]
Hi custom theme custom demo...

Working on vagrant (custom box based on scotchbox ), Cloudways, Eleven2

**Comment by eduplessis** [comment]
Multiple demo minimum size between 69mb and 120mb

**Comment by moldcraft** [comment]
Please find apache error.log and give us the error messages. If you can't find it, add [this script](http://sourcebox.io/8b8c68d8abcbf4b13f5197c13142d38a/php) (read the Usage part) in `functions.php` then run the install again to reproduce the problem

**Comment by eduplessis** [comment]
http://putsreq.com/UfgnasR6rRvTpTiBVExB/inspect

**Comment by eduplessis** [comment]
i gonna make a reset on putsreq and restart the call

**Comment by moldcraft** [comment]
> from putsreq
>
> `gzinflate(): data error in /home/mjutras/public_html/wp-includes/class-wp-http-encoding.php on line 58`

I see first time such error.
Can you give me admin/ftp access to your site so I will debug it myself? If yes, send the details to `moldcraft[at]email.com`

**Comment by eduplessis** [comment]
Sent you all the info

**Comment by moldcraft** [comment]
`gzinflate(): data error` I don't know how to fix it https://core.trac.wordpress.org/ticket/22952

But I think the problem is that the zip is very big and php can't unzip it. It will be very helpful to have access to error.log to see exactly which error happened (I am not sure that [this script](http://sourcebox.io/8b8c68d8abcbf4b13f5197c13142d38a/php) can catch all errors, especially timeout)

Please ask you hosting to send you or give access to apache error.log

**Comment by eduplessis** [comment]
ok we drop the size of the demo from 120mb to 40mb ... now working...

**Comment by moldcraft** [comment]
How you managed to make such a big drop?

**Comment by eduplessis** [comment]
We've checked all files in the archive and there was a lot of duplicate.... mp3 files... and images files there was all in double

**Comment by eduplessis** [comment]
For the other change https://github.com/ThemeFuse/Unyson-Backups-Extension/issues/8

It will be very nice to...
